# Generated by Django 5.0.6 on 2024-06-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis', to='aplikasi.merek')),
            ],
        ),
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penggerakroda', models.CharField(choices=[('2x4', '2x4'), ('4x4', '4x4')], default='2x4', max_length=3)),
                ('tahun', models.CharField(max_length=4)),
                ('odometer', models.CharField(max_length=7)),
                ('bahanbakar', models.CharField(choices=[('bensin', 'Bensin'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='bensin', max_length=10)),
                ('transmisi', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('kapasitas_mesin', models.CharField(choices=[('1000CC', '1000 CC'), ('1200CC', '1200 CC'), ('1400CC', '1400 CC'), ('1500CC', '1500 CC'), ('1600CC', '1600 CC'), ('1800CC', '1800 CC'), ('2000CC', '2000 CC'), ('2200CC', '2200 CC'), ('2400CC', '2400 CC'), ('2500CC', '2500 CC'), ('2600CC', '2600 CC'), ('2800CC', '2800 CC'), ('3000CC', '3000 CC')], max_length=7)),
                ('warna', models.CharField(max_length=20)),
                ('harga', models.CharField(max_length=15)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi.jenis')),
                ('merek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi.merek')),
            ],
        ),
    ]
