# Generated by Django 5.0.6 on 2024-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='kelayakan',
            field=models.CharField(choices=[('layak', 'Layak'), ('tidak Layak', 'Tidak Layak')], default='tidak Layak', max_length=11),
        ),
    ]
