# Generated by Django 5.0.6 on 2024-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0002_mobil_kelayakan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='kelayakan',
            field=models.CharField(choices=[('layak', 'Layak'), ('Tidak Layak', 'Tidak Layak')], default='Tidak Layak', max_length=11),
        ),
    ]
