# Generated by Django 5.0.6 on 2024-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0003_alter_mobil_kelayakan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='bahanbakar',
            field=models.CharField(choices=[('BENSIN', 'BENSIN'), ('DIESEL', 'DIESEL'), ('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID')], default='BENSIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='kelayakan',
            field=models.CharField(choices=[('LAYAK', 'LAYAK'), ('TIDAK LAYAK', 'TIDAK LAYAK')], default='TIDAK LAYAK', max_length=11),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='transmisi',
            field=models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=10),
        ),
    ]
